### paper_model: InternVL-3.5-4B
### model
model_name_or_path: OpenGVLab/InternVL3_5-4B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: rm
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_target: all

### dataset
dataset: medjudge_rm
eval_dataset: medjudge_rm_test
dataset_dir: /path/to/Medthink/LLaMA-Factory/data
template: intern_vl
cutoff_len: 8196
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /path/to/Medthink/outputs/internvl35_4b/medjudge_rm
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: "no"
